application:
   bitcoinBase: http://localhost:8332
gaia:
   challengeText: '["gaiahub","2018","","blockstack_storage_please_sign"]'
   readUrlShort: https://brightblock.s3.amazonaws.com/
   readUrlPrefix: https://s3.eu-west-2.amazonaws.com/brightblock/
   latestAuthVersion: v1
   storageRootDirectory: /tmp/gaia-disk
dropbox:
   apiKey: fanqyccblkttjs1
   apiSecret: tm4yaovo78czqi4
aws:
   configSecret: 
   serverName: server
   port: 3000
   driver: aws
   bucket: brightblock
   readUrlShort: https://brightblock.s3.amazonaws.com/
   readUrlPrefix: https://s3.eu-west-2.amazonaws.com/brightblock/
   argsTransport:
      level: warn
      handleExceptions: true
      stringify: true
      timestamp: true
      colorize: false
      json: true
   proofs:
      proofsRequired: 0

---

spring:
    profiles: test
application:
   bitcoinBase: http://localhost:8332

---

spring:
    profiles: docker-dev
application:
   bitcoinBase: http://docker.for.mac.localhost:8332

---

spring:
    profiles: staging
application:
   bitcoinBase: http://172.18.0.1:8332
               
---

spring:
    profiles: production
application:
   bitcoinBase: http://172.18.0.1:8332

