application:
   bitcoinBase: http://localhost:8332
gaia:
   challengeText: text-which-must-be-signed-to-validate-requests
   readUrlPrefix: https://gaia.brightblock.org/read/
   latestAuthVersion: v1
   storageRootDirectory: /tmp/gaia-disk

---

spring:
    profiles: test
application:
   bitcoinBase: http://localhost:8332

---

spring:
    profiles: docker-dev
application:
   bitcoinBase: http://docker.for.mac.localhost:8332

---

spring:
    profiles: staging
application:
   bitcoinBase: http://172.18.0.1:8332
               
---

spring:
    profiles: production
application:
   bitcoinBase: http://172.18.0.1:8332

